ARG COMPILER_IMAGE
FROM ${COMPILER_IMAGE:-wacruit-judge-compilers} AS production

RUN apt-get update && \
    apt-get install -y libmysqlclient-dev && \
    apt-get install -y --no-install-recommends \
      cron \
      libpq-dev \
      sudo && \
    rm -rf /var/lib/apt/lists/* && \
    echo "gem: --no-document" > /root/.gemrc && \
    gem install bundler:2.1.4 && \
    npm install -g --unsafe-perm aglio@2.3.0

ENV VIRTUAL_PORT 2358
EXPOSE $VIRTUAL_PORT

WORKDIR /api

COPY Gemfile* ./
RUN RAILS_ENV=production bundle

COPY cron /etc/cron.d
RUN cat /etc/cron.d/* | crontab -

COPY . .

ENV JUDGE0_VERSION "1.13.0"
LABEL version=$JUDGE0_VERSION

ENTRYPOINT ["/api/docker-entrypoint.sh"]
CMD ["/api/scripts/server"]