# Start with Ubuntu base image
FROM ubuntu:latest

# Set non-interactive environment variable
ENV DEBIAN_FRONTEND=noninteractive

# Update the system
RUN apt-get update -y
RUN apt-get upgrade -y

# Install common tools
RUN apt-get install -y curl wget git vim unzip zip

# Install Kotlin
RUN curl -s https://get.sdkman.io | bash
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin"

# Install Swift 5.7
RUN apt-get install -y binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata uuid-dev
RUN wget https://swift.org/builds/swift-5.7-release/ubuntu2004/swift-5.7-RELEASE/swift-5.7-RELEASE-ubuntu20.04.tar.gz
RUN tar xzf swift-5.7-RELEASE-ubuntu20.04.tar.gz
RUN echo 'export PATH=/swift-5.7-RELEASE-ubuntu20.04/usr/bin:"${PATH}"' >> ~/.bashrc
RUN rm swift-5.7-RELEASE-ubuntu20.04.tar.gz

# Install Java
RUN apt-get install -y openjdk-17-jdk

# Install C and C++
RUN apt-get install -y gcc g++

# Install Python 3 and pip
RUN apt-get install -y python3 python3-pip

# Install Node.js for JavaScript and TypeScript
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

# Install Typescript
RUN npm install -g typescript

# Install Ruby
# RUN apt-get update && apt-get install -y ruby-full ruby-dev
RUN set -xe && \
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash

ENV PATH /root/.rbenv/bin:$PATH
RUN set -xe && \
    rbenv install 2.7.0

ENV PATH /root/.rbenv/versions/2.7.0/bin:$PATH
    
# Install isolate
RUN set -xe && \
    apt-get update && \
    apt-get install -y --no-install-recommends git libcap-dev libsystemd-dev && \
    rm -rf /var/lib/apt/lists/* && \
    git clone -b cg2 https://github.com/ioi/isolate.git /tmp/isolate && \
    cd /tmp/isolate && \
    make -j$(nproc) install && \
    rm -rf /tmp/*
ENV BOX_ROOT /var/local/lib/isolate

# Clean up
RUN apt-get clean
