# Start with Ubuntu base image
FROM ubuntu:latest

# Set non-interactive environment variable
ENV DEBIAN_FRONTEND=noninteractive

# Update the system
RUN apt-get update -y
RUN apt-get upgrade -y

# Install common tools
RUN apt-get install -y curl wget git vim unzip zip && \
    apt-get clean

# Install Java & Kotlin & Scala
RUN apt-get install -y openjdk-8-jdk && \
    curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin 1.8.0 && sdk install scala 2.13.10" && \
    apt-get clean

# Install Swift 5.7
RUN apt-get install -y binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata uuid-dev && \
    wget https://swift.org/builds/swift-5.7-release/ubuntu2004/swift-5.7-RELEASE/swift-5.7-RELEASE-ubuntu20.04.tar.gz && \
    tar xzf swift-5.7-RELEASE-ubuntu20.04.tar.gz && \
    echo 'export PATH=/swift-5.7-RELEASE-ubuntu20.04/usr/bin:"${PATH}"' >> ~/.bashrc && \
    rm swift-5.7-RELEASE-ubuntu20.04.tar.gz && \
    apt-get clean

# Install C and C++
RUN apt-get install -y gcc g++ && \
    apt-get clean

# Install Python 3 and pip
RUN apt-get install -y python3 python3-pip && \
    apt-get clean

# Install Node.js for JavaScript and TypeScript
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs && \
    apt-get clean

# Install Typescript
RUN npm install -g typescript

# Install Sqlite3
RUN set -xe && \
    apt-get update && \
    apt-get install -y --no-install-recommends sqlite3 && \
    rm -rf /var/lib/apt/lists/*

# Install Go
RUN set -xe && \
    wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz && \
    rm go1.17.2.linux-amd64.tar.gz

# Install Ruby
# RUN apt-get update && apt-get install -y ruby-full ruby-dev
RUN set -xe && \
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash

ENV PATH /root/.rbenv/bin:$PATH
RUN set -xe && \
    rbenv install 2.7.0

ENV PATH /root/.rbenv/versions/2.7.0/bin:$PATH
    
# Install isolate
RUN set -xe && \
    apt-get update && \
    apt-get install -y --no-install-recommends git libcap-dev libsystemd-dev && \
    rm -rf /var/lib/apt/lists/* && \
    git clone -b master https://github.com/ioi/isolate.git /tmp/isolate && \
    cd /tmp/isolate && \
    make -j$(nproc) install && \
    rm -rf /tmp/* && \
    apt-get clean

ENV BOX_ROOT /var/local/lib/isolate
