#!/bin/bash
source ./scripts/load-config

[[ -f tmp/pids/server.pid ]] && rm -f tmp/pids/server.pid

export DISABLE_DATABASE_ENVIRONMENT_CHECK=1

rails db:create db:migrate db:seed
rails s -b 0.0.0.0
