#!/bin/bash
# Script for running Judge0 server.
#
# Usage: ./scripts/server
#
for i in $(seq 1 $RESTART_MAX_TRIES); do
    source ./scripts/load-config

    [[ -f tmp/pids/server.pid ]] && rm -f tmp/pids/server.pid

    rails db:create db:migrate db:seed
    rails s -b 0.0.0.0
    [[ $? -eq 0 ]] && break
    sleep 2s
done
