#!/bin/bash
pushd "$(git rev-parse --show-toplevel)"

source ./scripts/dev/utils/info

if [[ -v CACHE ]]; then
    docker pull $CACHE
    CACHE="--cache-from $CACHE"
fi

function build_and_tag() {
    target=$1
    images=($2)
    main_image=${images[0]}

    echo Main image: $main_image
    docker build -t $main_image $CACHE --target $target

    i=1
    while true; do
        image=${images[i]}
        if [[ "$image" == "" ]]; then
            break
        fi
        echo $image
        docker tag $main_image $image
        i=$((i + 1))
    done
}

build_and_tag production "$JUDGE0_PRODUCTION_IMAGES"
build_and_tag development "$JUDGE0_DEVELOPMENT_IMAGES"

popd
