#!/bin/bash
# Script for removing the Judge0 API development
# environment (containers and volumes).
#
# Usage: ./scripts/dev/clean
#
docker-compose -f docker-compose.dev.yml down
docker-compose -f docker-compose.dev.yml down -v
