#!/bin/bash
# Script for creating a new or using existing
# Judge0 development environment and
# opening new shell inside Judge0 container.
#
# Usage: ./scripts/dev/shell
#
docker-compose -f docker-compose.dev.yml up -d
docker-compose -f docker-compose.dev.yml exec --privileged judge0 bash
