#!/bin/bash
# Script for creating a new or using existing
# Judge0 API development environment and
# opening new shell inside Judge0 API container.
#
# Usage: ./scripts/dev/shell
#
docker-compose -f docker-compose.dev.yml up -d
docker-compose -f docker-compose.dev.yml exec --privileged api bash
